# Generated by Django 3.2.3 on 2021-10-10 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, default='Admin', max_length=50, null=True, verbose_name='Admin Name')),
                ('admin_contact_number', models.PositiveIntegerField(default=0, verbose_name='Contact No.')),
                ('admin_image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='User/Admin_Images')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Username')),
                ('user_mobile_number', models.PositiveIntegerField(default=0, verbose_name='Mobile No.')),
                ('user_enrollment_number', models.PositiveIntegerField(default=0, verbose_name='Enrollment No.')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_verified_email', models.BooleanField(default=False, verbose_name='is_verified_email')),
                ('is_verified_mobile', models.BooleanField(default=False, verbose_name='is_verified_mobile')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('user_device_id', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='user_device_id')),
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_department_id', to='University.tbldepartments')),
                ('institute_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_institute_id', to='University.tblinstitutes')),
            ],
        ),
        migrations.CreateModel(
            name='TblPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='Admin', max_length=100, null=True, verbose_name='Role')),
                ('can_view', models.BooleanField(default=True, verbose_name='can_view')),
                ('can_edit', models.BooleanField(default=False, verbose_name='can_edit')),
                ('can_insert', models.BooleanField(default=False, verbose_name='can_insert')),
                ('can_delete', models.BooleanField(default=False, verbose_name='can_delete')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_admin_id', to='User.tbladmin')),
            ],
        ),
        migrations.AddField(
            model_name='tbladmin',
            name='account_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
