# Generated by Django 3.2.3 on 2022-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_auto_20220126_1414'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbladmin',
            name='allowed_courses',
            field=models.ManyToManyField(to='University.TblCourses'),
        ),
        migrations.AddField(
            model_name='tbladmin',
            name='allowed_department',
            field=models.ManyToManyField(to='University.TblDepartments'),
        ),
        migrations.AddField(
            model_name='tbladmin',
            name='allowed_institute',
            field=models.ManyToManyField(to='University.TblInstitutes'),
        ),
        migrations.AddField(
            model_name='tbladmin',
            name='allowed_university',
            field=models.ManyToManyField(to='University.TblUniversity'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tbladmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblpermissions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
