# Generated by Django 3.2.3 on 2021-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpermissions',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='can_view'),
        ),
    ]
