# Generated by Django 3.2.3 on 2022-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_auto_20220126_1414'),
        ('User', '0002_auto_20220126_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbladmin',
            name='allowed_courses',
        ),
        migrations.RemoveField(
            model_name='tbladmin',
            name='allowed_department',
        ),
        migrations.RemoveField(
            model_name='tbladmin',
            name='allowed_institute',
        ),
        migrations.RemoveField(
            model_name='tbladmin',
            name='allowed_university',
        ),
        migrations.AddField(
            model_name='tblpermissions',
            name='allowed_courses',
            field=models.ManyToManyField(to='University.TblCourses'),
        ),
        migrations.AddField(
            model_name='tblpermissions',
            name='allowed_department',
            field=models.ManyToManyField(to='University.TblDepartments'),
        ),
        migrations.AddField(
            model_name='tblpermissions',
            name='allowed_institute',
            field=models.ManyToManyField(to='University.TblInstitutes'),
        ),
        migrations.AddField(
            model_name='tblpermissions',
            name='allowed_university',
            field=models.ManyToManyField(to='University.TblUniversity'),
        ),
    ]
