# Generated by Django 3.2.3 on 2021-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210916_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpermissions',
            name='role_id',
        ),
        migrations.AddField(
            model_name='tblpermissions',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='TblRoles',
        ),
    ]
