# Generated by Django 3.2.3 on 2022-02-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('University', '0001_initial'),
        ('Appartus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFixedInputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_input_parameter_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Fixed Input Parameter')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblFixedOutputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_output_parameter_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Fixed Output Parameter')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblInputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_parameter_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Input Parameter')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblPractical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Practical Name')),
                ('practical_feature_image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='Practical/Practical-Feature-Images')),
                ('practical_procedure', models.TextField(blank=True, default='', null=True, verbose_name='Procedure')),
                ('practical_application', models.TextField(blank=True, default='', null=True, verbose_name='Application')),
                ('practical_advantages', models.TextField(blank=True, default='', null=True, verbose_name='Advantages')),
                ('practical_conclusion', models.TextField(blank=True, default='', null=True, verbose_name='Conclusion')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='University.tblcourses')),
            ],
        ),
        migrations.CreateModel(
            name='TblParameterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_file', models.FileField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='Practical/Parameter-Files/{practical_id.practical_name}')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblOutputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_parameter_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Output Parameter')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleYoutubeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_title', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Title')),
                ('youtube_video_links', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Youtube Link')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultiplePracticalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='Practical/Multiple-Practical-Images/{practical_id.practical_name}')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleOutputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_parameter_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Output Parameter Name')),
                ('output_parameter_value', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Output Parameter Value')),
                ('output_parameter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tbloutputparameter')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Material Name')),
                ('material_file_path', models.FileField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='Practical/Materials/{practical_id.practical_name}')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleInputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_parameter_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Input Parameter Name')),
                ('input_parameter_value', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Input Parameter Value')),
                ('input_parameter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblinputparameter')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleFixedOutputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_output_parameter_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Fixed Output Parameter Name')),
                ('fixed_output_parameter_value', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Fixed Output Parameter Value')),
                ('fixed_output_parameter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblfixedoutputparameter')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleFixedInputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_input_parameter_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Fixed Input Parameter Name')),
                ('fixed_input_parameter_value', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Fixed Input Parameter Value')),
                ('fixed_input_parameter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblfixedinputparameter')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.CreateModel(
            name='TblMultipleAppartus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appartus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appartus.tblappartus')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
        migrations.AddField(
            model_name='tblinputparameter',
            name='practical_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical'),
        ),
        migrations.AddField(
            model_name='tblfixedoutputparameter',
            name='practical_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical'),
        ),
        migrations.AddField(
            model_name='tblfixedinputparameter',
            name='practical_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical'),
        ),
    ]
