# Generated by Django 3.2.3 on 2021-10-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblParameterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_file', models.FileField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='Practical/Parameter-Files/{practical_id.practical_name}')),
                ('practical_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Practical.tblpractical')),
            ],
        ),
    ]
