# Generated by Django 3.2.3 on 2021-09-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblfixedinputparameter',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblfixedoutputparameter',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblinputparameter',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbloutputparameter',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblpractical',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
