# Generated by Django 3.1.4 on 2021-10-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='University Name')),
                ('university_unique_num', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Unique No.')),
                ('university_address', models.TextField(blank=True, default='', null=True, verbose_name='Address')),
                ('university_city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='City')),
                ('university_state', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='State')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblInstitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Institute Name')),
                ('institute_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Institute Code')),
                ('institute_address', models.TextField(blank=True, default='', null=True, verbose_name='Address')),
                ('institute_city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='City')),
                ('institute_state', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='State')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('university_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='University.tbluniversity')),
            ],
        ),
        migrations.CreateModel(
            name='TblDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Department Name')),
                ('department_contact_person', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Contact Person')),
                ('department_contact', models.PositiveIntegerField(default=0, verbose_name='Contact No.')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('institute_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='University.tblinstitutes')),
            ],
        ),
        migrations.CreateModel(
            name='TblCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Courses Name')),
                ('courses_code', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Courses Code')),
                ('courses_syllabus', models.TextField(blank=True, default='', null=True, verbose_name='Syllabus')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('insert_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='University.tbldepartments')),
            ],
        ),
    ]
