# Generated by Django 3.2.3 on 2021-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluniversity',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
