# Generated by Django 3.2.3 on 2021-09-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_alter_tbluniversity_update_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcourses',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbldepartments',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblinstitutes',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
