from django.urls import path
from .views import *

urlpatterns = [
    # ========================Admin Panel===========================
    path('', login_page, name='login'),
    path('profile/', profile, name='profile'),
    path('change_password/', change_password, name='change_password'),
    path('register_admin/', register_admin, name='register_admin'),
    path('register_director/', register_director, name='register_director'),
    path('register_principal/', register_principal, name='register_principal'),
    path('register_hod/', register_hod, name='register_hod'),
    path('register_faculty/', register_faculty, name='register_faculty'),
    path('view_admin/', view_admin, name='view_admin'),
    path('view_director/', view_director, name='view_director'),
    path('view_principal/', view_principal, name='view_principal'),
    path('view_hod/', view_hod, name='view_hod'),
    path('view_faculty/', view_faculty, name='view_faculty'),
    path('update_admin/<int:key>', update_admin, name='update_admin'),
    path('update_director/<int:key>', update_director, name='update_director'),
    path('update_principal/<int:key>', update_principal, name='update_principal'),
    path('update_hod/<int:key>', update_hod, name='update_hod'),
    path('update_faculty/<int:key>', update_faculty, name='update_faculty'),
    path('delete_admin/<int:key>', delete_admin, name='delete_admin'),
    path('delete_director/<int:key>', delete_director, name='delete_director'),
    path('delete_principal/<int:key>', delete_principal, name='delete_principal'),
    path('delete_hod/<int:key>', delete_hod, name='delete_hod'),
    path('delete_faculty/<int:key>', delete_faculty, name='delete_faculty'),
    path('logout/', logout_page, name='logout'),
    path('sel_institute/', sel_institute, name='sel_institute'),
    path('sel_department/', sel_department, name='sel_department'),
    path('sel_courses/', sel_courses, name='sel_courses'),
    path('update_institute/', update_institute, name='update_institute'),
    path('update_department/', update_department, name='update_department'),
    path('update_courses/', update_courses, name='update_courses'),

    path('view_requests/', view_requests, name='view_requests'),
    path('approve_student/<int:id>', approve_student, name='approve_student'),
    path('decline_student/<int:id>', decline_student, name='decline_student'),
    path('view_accepted_students/', view_accepted_students, name='view_accepted_students'),
]
